/**
 * Client-side mirror of backend/app/services/dcf.py::run_dcf, used by the
 * landing-page demo and the report's what-if panel (no API calls). Report
 * figures, the range chart and the PDF always come from the backend. Parity with
 * the Python engine is enforced by lib/dcf-engine.test.mjs and
 * lib/dcf-scenario.test.mjs against values generated by the backend itself.
 */

export interface DcfInputs {
  latestRevenue: number;
  growthRates: [number, number, number, number, number];
  ebitMargin: number;
  taxRate: number;
  daPct: number;
  capexPct: number;
  wcPct: number;
  wacc: number;
  terminalGrowth: number;
  totalDebt: number;
  cash: number;
  sharesOutstanding: number;
}

export interface DcfYear {
  year: number;
  revenue: number;
  ebit: number;
  nopat: number;
  fcff: number;
  discountFactor: number;
  pvFcff: number;
}

export type DcfOutput =
  | {
      ok: true;
      projections: DcfYear[];
      terminalValue: number;
      pvTerminalValue: number;
      enterpriseValue: number;
      netDebt: number;
      equityValue: number;
      perShare: number;
      terminalShare: number;
    }
  | { ok: false; reason: string };

export function runDcf(inputs: DcfInputs): DcfOutput {
  const { wacc, terminalGrowth } = inputs;
  if (!Number.isFinite(wacc) || !Number.isFinite(terminalGrowth)) {
    return { ok: false, reason: "WACC and terminal growth must be finite." };
  }
  if (wacc <= terminalGrowth) {
    return { ok: false, reason: "WACC must exceed terminal growth for the Gordon Growth terminal value." };
  }
  if (!(inputs.latestRevenue > 0)) {
    return { ok: false, reason: "Latest revenue must be positive." };
  }
  if (!(inputs.sharesOutstanding > 0)) {
    return { ok: false, reason: "Shares outstanding must be positive." };
  }

  const projections: DcfYear[] = [];
  let revenue = inputs.latestRevenue;
  for (let year = 1; year <= 5; year += 1) {
    revenue *= 1 + inputs.growthRates[year - 1];
    const ebit = revenue * inputs.ebitMargin;
    const nopat = ebit * (1 - inputs.taxRate);
    const fcff = nopat + revenue * inputs.daPct - revenue * inputs.capexPct - revenue * inputs.wcPct;
    const discountFactor = 1 / (1 + wacc) ** year;
    projections.push({ year, revenue, ebit, nopat, fcff, discountFactor, pvFcff: fcff * discountFactor });
  }

  const fcff5 = projections[4].fcff;
  const terminalValue = (fcff5 * (1 + terminalGrowth)) / (wacc - terminalGrowth);
  const pvTerminalValue = terminalValue / (1 + wacc) ** 5;
  const enterpriseValue = projections.reduce((sum, p) => sum + p.pvFcff, 0) + pvTerminalValue;
  const netDebt = inputs.totalDebt - inputs.cash;
  const equityValue = enterpriseValue - netDebt;
  const perShare = equityValue / inputs.sharesOutstanding;

  if (![enterpriseValue, equityValue, perShare].every(Number.isFinite)) {
    return { ok: false, reason: "Inputs produce a non-finite valuation." };
  }

  return {
    ok: true,
    projections,
    terminalValue,
    pvTerminalValue,
    enterpriseValue,
    netDebt,
    equityValue,
    perShare,
    terminalShare: enterpriseValue !== 0 ? pvTerminalValue / enterpriseValue : Number.NaN,
  };
}

/** Same fade schedule as compute_assumptions_from_history: Y1 → terminal. */
export function fadeSchedule(y1: number, terminal: number): [number, number, number, number, number] {
  const y2 = y1 - (y1 - terminal) * 0.2;
  const y3 = y2 + (terminal - y2) * (1 / 3);
  const y4 = y2 + (terminal - y2) * (2 / 3);
  return [y1, y2, y3, y4, terminal];
}
